import { SearchItems } from "../types/SearchItems";

export const searchItems: SearchItems[] = [
	{
		range: "spoken_language",
		label: "Spoken Language",
		active: true,
		selected: "",
		param: "spoken_language_code",
		categories: [
			{ value: "", label: "Any" },
			{ value: "ab", label: "Abkhazian" },
			{ value: "aa", label: "Afar" },
			{ value: "af", label: "Afrikaans" },
			{ value: "ak", label: "Akan" },
			{ value: "sq", label: "Albanian" },
			{ value: "am", label: "Amharic" },
			{ value: "ar", label: "Arabic" },
			{ value: "an", label: "Aragonese" },
			{ value: "hy", label: "Armenian" },
			{ value: "as", label: "Assamese" },
			{ value: "av", label: "Avaric" },
			{ value: "ae", label: "Avestan" },
			{ value: "ay", label: "Aymara" },
			{ value: "az", label: "Azerbaijani" },
			{ value: "bm", label: "Bambara" },
			{ value: "ba", label: "Bashkir" },
			{ value: "eu", label: "Basque" },
			{ value: "be", label: "Belarusian" },
			{ value: "bn", label: "Bengali" },
			{ value: "bh", label: "Bihari languages" },
			{ value: "bi", label: "Bislama" },
			{ value: "bs", label: "Bosnian" },
			{ value: "br", label: "Breton" },
			{ value: "bg", label: "Bulgarian" },
			{ value: "my", label: "Burmese" },
			{ value: "ca", label: "Catalan, Valencian" },
			{ value: "ch", label: "Chamorro" },
			{ value: "ce", label: "Chechen" },
			{ value: "ny", label: "Chichewa, Chewa, Nyanja" },
			{ value: "zh", label: "Chinese" },
			{ value: "cv", label: "Chuvash" },
			{ value: "kw", label: "Cornish" },
			{ value: "co", label: "Corsican" },
			{ value: "cr", label: "Cree" },
			{ value: "hr", label: "Croatian" },
			{ value: "cs", label: "Czech" },
			{ value: "da", label: "Danish" },
			{ value: "dv", label: "Divehi, Dhivehi, Maldivian" },
			{ value: "nl", label: "Dutch, Flemish" },
			{ value: "dz", label: "Dzongkha" },
			{ value: "en", label: "English" },
			{ value: "eo", label: "Esperanto" },
			{ value: "et", label: "Estonian" },
			{ value: "ee", label: "Ewe" },
			{ value: "fo", label: "Faroese" },
			{ value: "fj", label: "Fijian" },
			{ value: "fi", label: "Finnish" },
			{ value: "fr", label: "French" },
			{ value: "ff", label: "Fulah" },
			{ value: "gl", label: "Galician" },
			{ value: "ka", label: "Georgian" },
			{ value: "de", label: "German" },
			{ value: "el", label: "Greek, Modern" },
			{ value: "gn", label: "Guarani" },
			{ value: "gu", label: "Gujarati" },
			{ value: "ht", label: "Haitian, Haitian Creole" },
			{ value: "ha", label: "Hausa" },
			{ value: "he", label: "Hebrew" },
			{ value: "hz", label: "Herero" },
			{ value: "hi", label: "Hindi" },
			{ value: "ho", label: "Hiri Motu" },
			{ value: "hu", label: "Hungarian" },
			{ value: "ia", label: "Interlingua (International Auxil..." },
			{ value: "id", label: "Indonesian" },
			{ value: "ie", label: "Interlingue, Occidental" },
			{ value: "ga", label: "Irish" },
			{ value: "ig", label: "Igbo" },
			{ value: "ik", label: "Inupiaq" },
			{ value: "io", label: "Ido" },
			{ value: "is", label: "Icelandic" },
			{ value: "it", label: "Italian" },
			{ value: "iu", label: "Inuktitut" },
			{ value: "ja", label: "Japanese" },
			{ value: "jv", label: "Javanese" },
			{ value: "kl", label: "Kalaallisut, Greenlandic" },
			{ value: "kn", label: "Kannada" },
			{ value: "kr", label: "Kanuri" },
			{ value: "ks", label: "Kashmiri" },
			{ value: "kk", label: "Kazakh" },
			{ value: "km", label: "Central Khmer" },
			{ value: "ki", label: "Kikuyu, Gikuyu" },
			{ value: "rw", label: "Kinyarwanda" },
			{ value: "ky", label: "Kirghiz, Kyrgyz" },
			{ value: "kv", label: "Komi" },
			{ value: "kg", label: "Kongo" },
			{ value: "ko", label: "Korean" },
			{ value: "ku", label: "Kurdish" },
			{ value: "kj", label: "Kuanyama, Kwanyama" },
			{ value: "la", label: "Latin" },
			{ value: "lb", label: "Luxembourgish, Letzeburgesch" },
			{ value: "lg", label: "Ganda" },
			{ value: "li", label: "Limburgan, Limburger, Limburgish" },
			{ value: "ln", label: "Lingala" },
			{ value: "lo", label: "Lao" },
			{ value: "lt", label: "Lithuanian" },
			{ value: "lu", label: "Luba-Katanga" },
			{ value: "lv", label: "Latvian" },
			{ value: "gv", label: "Manx" },
			{ value: "mk", label: "Macedonian" },
			{ value: "mg", label: "Malagasy" },
			{ value: "ms", label: "Malay" },
			{ value: "ml", label: "Malayalam" },
			{ value: "mt", label: "Maltese" },
			{ value: "mi", label: "Maori" },
			{ value: "mr", label: "Marathi" },
			{ value: "mh", label: "Marshallese" },
			{ value: "mn", label: "Mongolian" },
			{ value: "na", label: "Nauru" },
			{ value: "nv", label: "Navajo, Navaho" },
			{ value: "nd", label: "North Ndebele" },
			{ value: "ne", label: "Nepali" },
			{ value: "ng", label: "Ndonga" },
			{ value: "nb", label: "Norwegian Bokmål" },
			{ value: "nn", label: "Norwegian Nynorsk" },
			{ value: "no", label: "Norwegian" },
			{ value: "ii", label: "Sichuan Yi, Nuosu" },
			{ value: "nr", label: "South Ndebele" },
			{ value: "oc", label: "Occitan" },
			{ value: "oj", label: "Ojibwa" },
			{ value: "cu", label: "Church Slavic, Old Slavonic, Chu..." },
			{ value: "om", label: "Oromo" },
			{ value: "or", label: "Oriya" },
			{ value: "os", label: "Ossetian, Ossetic" },
			{ value: "pa", label: "Punjabi, Panjabi" },
			{ value: "pi", label: "Pali" },
			{ value: "fa", label: "Persian" },
			{ value: "pl", label: "Polish" },
			{ value: "ps", label: "Pashto, Pushto" },
			{ value: "pt", label: "Portuguese" },
			{ value: "qu", label: "Quechua" },
			{ value: "rm", label: "Romansh" },
			{ value: "rn", label: "Rundi" },
			{ value: "ro", label: "Romanian, Moldavian, Moldovan" },
			{ value: "ru", label: "Russian" },
			{ value: "sa", label: "Sanskrit" },
			{ value: "sc", label: "Sardinian" },
			{ value: "sd", label: "Sindhi" },
			{ value: "se", label: "Northern Sami" },
			{ value: "sm", label: "Samoan" },
			{ value: "sg", label: "Sango" },
			{ value: "sr", label: "Serbian" },
			{ value: "gd", label: "Gaelic, Scottish Gaelic" },
			{ value: "sn", label: "Shona" },
			{ value: "si", label: "Sinhala, Sinhalese" },
			{ value: "sk", label: "Slovak" },
			{ value: "sl", label: "Slovenian" },
			{ value: "so", label: "Somali" },
			{ value: "st", label: "Southern Sotho" },
			{ value: "es", label: "Spanish, Castilian" },
			{ value: "su", label: "Sundanese" },
			{ value: "sw", label: "Swahili" },
			{ value: "ss", label: "Swati" },
			{ value: "sv", label: "Swedish" },
			{ value: "ta", label: "Tamil" },
			{ value: "te", label: "Telugu" },
			{ value: "tg", label: "Tajik" },
			{ value: "th", label: "Thai" },
			{ value: "ti", label: "Tigrinya" },
			{ value: "bo", label: "Tibetan" },
			{ value: "tk", label: "Turkmen" },
			{ value: "tl", label: "Tagalog" },
			{ value: "tn", label: "Tswana" },
			{ value: "to", label: "Tonga (Tonga Islands)" },
			{ value: "tr", label: "Turkish" },
			{ value: "ts", label: "Tsonga" },
			{ value: "tt", label: "Tatar" },
			{ value: "tw", label: "Twi" },
			{ value: "ty", label: "Tahitian" },
			{ value: "ug", label: "Uighur, Uyghur" },
			{ value: "uk", label: "Ukrainian" },
			{ value: "ur", label: "Urdu" },
			{ value: "uz", label: "Uzbek" },
			{ value: "ve", label: "Venda" },
			{ value: "vi", label: "Vietnamese" },
			{ value: "vo", label: "Volapük" },
			{ value: "wa", label: "Walloon" },
			{ value: "cy", label: "Welsh" },
			{ value: "wo", label: "Wolof" },
			{ value: "fy", label: "Western Frisian" },
			{ value: "xh", label: "Xhosa" },
			{ value: "yi", label: "Yiddish" },
			{ value: "yo", label: "Yoruba" },
			{ value: "za", label: "Zhuang, Chuang" },
			{ value: "zu", label: "Zulu" },
		],
	},
	{
		range: "language",
		label: "Language",
		active: true,
		selected: "",
		param: "language_code",
		categories: [
			{ value: "", label: "Any" },
			{ value: "c++", label: "C++" },
			{ value: "html", label: "HTML" },
			{ value: "java", label: "Java" },
			{ value: "javascript", label: "JavaScript" },
			{ value: "php", label: "PHP" },
			{ value: "python", label: "Python" },
			{ value: "ruby", label: "Ruby" },
			{ value: "unknown", label: "Unknown languages" },
			{ value: "1c-enterprise", label: "1C Enterprise" },
			{ value: "4d", label: "4D" },
			{ value: "abap", label: "ABAP" },
			{ value: "abap-cds", label: "ABAP CDS" },
			{ value: "abnf", label: "ABNF" },
			{ value: "actionscript", label: "ActionScript" },
			{ value: "ada", label: "Ada" },
			{ value: "adobe-font-metrics", label: "Adobe Font Metrics" },
			{ value: "agda", label: "Agda" },
			{ value: "ags-script", label: "AGS Script" },
			{ value: "aidl", label: "AIDL" },
			{ value: "al", label: "AL" },
			{ value: "al", label: "AL" },
			{ value: "alloy", label: "Alloy" },
			{ value: "alpine-abuild", label: "Alpine Abuild" },
			{ value: "altium-designer", label: "Altium Designer" },
			{ value: "ampl", label: "AMPL" },
			{ value: "angelscript", label: "AngelScript" },
			{ value: "ant-build-system", label: "Ant Build System" },
			{ value: "antlr", label: "ANTLR" },
			{ value: "apacheconf", label: "ApacheConf" },
			{ value: "apex", label: "Apex" },
			{ value: "api-blueprint", label: "API Blueprint" },
			{ value: "apl", label: "APL" },
			{ value: "apollo-guidance-computer", label: "Apollo Guidance Computer" },
			{ value: "applescript", label: "AppleScript" },
			{ value: "arc", label: "Arc" },
			{ value: "asciidoc", label: "AsciiDoc" },
			{ value: "asl", label: "ASL" },
			{ value: "asn.1", label: "ASN.1" },
			{ value: "classic-asp", label: "Classic ASP" },
			{ value: "asp.net", label: "ASP.NET" },
			{ value: "aspectj", label: "AspectJ" },
			{ value: "assembly", label: "Assembly" },
			{ value: "astro", label: "Astro" },
			{ value: "asymptote", label: "Asymptote" },
			{ value: "ats", label: "ATS" },
			{ value: "augeas", label: "Augeas" },
			{ value: "autohotkey", label: "AutoHotkey" },
			{ value: "autoit", label: "AutoIt" },
			{ value: "avro-idl", label: "Avro IDL" },
			{ value: "awk", label: "Awk" },
			{ value: "ballerina", label: "Ballerina" },
			{ value: "basic", label: "BASIC" },
			{ value: "batchfile", label: "Batchfile" },
			{ value: "beef", label: "Beef" },
			{ value: "befunge", label: "Befunge" },
			{ value: "bibtex", label: "BibTeX" },
			{ value: "bicep", label: "Bicep" },
			{ value: "bison", label: "Bison" },
			{ value: "bitbake", label: "BitBake" },
			{ value: "blade", label: "Blade" },
			{ value: "blitzbasic", label: "BlitzBasic" },
			{ value: "blitzmax", label: "BlitzMax" },
			{ value: "bluespec", label: "Bluespec" },
			{ value: "boo", label: "Boo" },
			{ value: "boogie", label: "Boogie" },
			{ value: "brainfuck", label: "Brainfuck" },
			{ value: "brightscript", label: "Brightscript" },
			{ value: "zeek", label: "Zeek" },
			{ value: "browserslist", label: "Browserslist" },
			{ value: "c", label: "C" },
			{ value: "c%23", label: "C#" },
			{ value: "c-objdump", label: "C-ObjDump" },
			{ value: "c2hs-haskell", label: "C2hs Haskell" },
			{ value: "cabal-config", label: "Cabal Config" },
			{ value: "cap'n-proto", label: "Cap'n Proto" },
			{ value: "cartocss", label: "CartoCSS" },
			{ value: "ceylon", label: "Ceylon" },
			{ value: "chapel", label: "Chapel" },
			{ value: "charity", label: "Charity" },
			{ value: "chuck", label: "ChucK" },
			{ value: "cil", label: "CIL" },
			{ value: "cirru", label: "Cirru" },
			{ value: "clarion", label: "Clarion" },
			{ value: "classic-asp", label: "Classic ASP" },
			{ value: "clean", label: "Clean" },
			{ value: "click", label: "Click" },
			{ value: "clips", label: "CLIPS" },
			{ value: "clojure", label: "Clojure" },
			{ value: "closure-templates", label: "Closure Templates" },
			{
				value: "cloud-firestore-security-rules",
				label: "Cloud Firestore Security Rules",
			},
			{ value: "cmake", label: "CMake" },
			{ value: "cobol", label: "COBOL" },
			{ value: "codeowners", label: "CODEOWNERS" },
			{ value: "codeql", label: "CodeQL" },
			{ value: "coffeescript", label: "CoffeeScript" },
			{ value: "coldfusion", label: "ColdFusion" },
			{ value: "coldfusion-cfc", label: "ColdFusion CFC" },
			{ value: "collada", label: "COLLADA" },
			{ value: "common-lisp", label: "Common Lisp" },
			{ value: "common-workflow-language", label: "Common Workflow Language" },
			{ value: "component-pascal", label: "Component Pascal" },
			{ value: "conll-u", label: "CoNLL-U" },
			{ value: "cool", label: "Cool" },
			{ value: "coq", label: "Coq" },
			{ value: "cpp-objdump", label: "Cpp-ObjDump" },
			{ value: "creole", label: "Creole" },
			{ value: "crystal", label: "Crystal" },
			{ value: "cson", label: "CSON" },
			{ value: "csound", label: "Csound" },
			{ value: "csound-document", label: "Csound Document" },
			{ value: "csound-score", label: "Csound Score" },
			{ value: "css", label: "CSS" },
			{ value: "csv", label: "CSV" },
			{ value: "cuda", label: "Cuda" },
			{ value: "cue", label: "CUE" },
			{ value: "curl-config", label: "cURL Config" },
			{ value: "cweb", label: "CWeb" },
			{ value: "cycript", label: "Cycript" },
			{ value: "cython", label: "Cython" },
			{ value: "d", label: "D" },
			{ value: "d-objdump", label: "D-ObjDump" },
			{ value: "dafny", label: "Dafny" },
			{ value: "darcs-patch", label: "Darcs Patch" },
			{ value: "dart", label: "Dart" },
			{ value: "dataweave", label: "DataWeave" },
			{ value: "desktop", label: "desktop" },
			{ value: "dhall", label: "Dhall" },
			{ value: "diff", label: "Diff" },
			{ value: "digital-command-language", label: "DIGITAL Command Language" },
			{ value: "dircolors", label: "dircolors" },
			{ value: "directx-3d-file", label: "DirectX 3D File" },
			{ value: "dm", label: "DM" },
			{ value: "dns-zone", label: "DNS Zone" },
			{ value: "dockerfile", label: "Dockerfile" },
			{ value: "dogescript", label: "Dogescript" },
			{ value: "dtrace", label: "DTrace" },
			{ value: "dylan", label: "Dylan" },
			{ value: "e", label: "E" },
			{ value: "e-mail", label: "E-mail" },
			{ value: "eagle", label: "Eagle" },
			{ value: "earthly", label: "Earthly" },
			{ value: "easybuild", label: "Easybuild" },
			{ value: "ebnf", label: "EBNF" },
			{ value: "ec", label: "eC" },
			{ value: "ecere-projects", label: "Ecere Projects" },
			{ value: "ecl", label: "ECL" },
			{ value: "eclipse", label: "ECLiPSe" },
			{ value: "editorconfig", label: "EditorConfig" },
			{ value: "edje-data-collection", label: "Edje Data Collection" },
			{ value: "edn", label: "edn" },
			{ value: "eiffel", label: "Eiffel" },
			{ value: "ejs", label: "EJS" },
			{ value: "elixir", label: "Elixir" },
			{ value: "elm", label: "Elm" },
			{ value: "emacs-lisp", label: "Emacs Lisp" },
			{ value: "emberscript", label: "EmberScript" },
			{ value: "e-mail", label: "E-mail" },
			{ value: "eq", label: "EQ" },
			{ value: "erlang", label: "Erlang" },
			{ value: "f%23", label: "F#" },
			{ value: "f*", label: "F*" },
			{ value: "factor", label: "Factor" },
			{ value: "fancy", label: "Fancy" },
			{ value: "fantom", label: "Fantom" },
			{ value: "faust", label: "Faust" },
			{ value: "fennel", label: "Fennel" },
			{ value: "figlet-font", label: "FIGlet Font" },
			{ value: "filebench-wml", label: "Filebench WML" },
			{ value: "filterscript", label: "Filterscript" },
			{ value: "fish", label: "fish" },
			{ value: "fluent", label: "Fluent" },
			{ value: "flux", label: "FLUX" },
			{ value: "formatted", label: "Formatted" },
			{ value: "forth", label: "Forth" },
			{ value: "fortran", label: "Fortran" },
			{ value: "fortran-free-form", label: "Fortran Free Form" },
			{ value: "freebasic", label: "FreeBasic" },
			{ value: "freemarker", label: "FreeMarker" },
			{ value: "frege", label: "Frege" },
			{ value: "futhark", label: "Futhark" },
			{ value: "g-code", label: "G-code" },
			{ value: "game-maker-language", label: "Game Maker Language" },
			{ value: "gaml", label: "GAML" },
			{ value: "gams", label: "GAMS" },
			{ value: "gap", label: "GAP" },
			{ value: "gcc-machine-description", label: "GCC Machine Description" },
			{ value: "gdb", label: "GDB" },
			{ value: "gdscript", label: "GDScript" },
			{ value: "gedcom", label: "GEDCOM" },
			{ value: "gemfile.lock", label: "Gemfile.lock" },
			{ value: "genie", label: "Genie" },
			{ value: "genshi", label: "Genshi" },
			{ value: "gentoo-ebuild", label: "Gentoo Ebuild" },
			{ value: "gentoo-eclass", label: "Gentoo Eclass" },
			{ value: "gerber-image", label: "Gerber Image" },
			{ value: "gettext-catalog", label: "Gettext Catalog" },
			{ value: "gherkin", label: "Gherkin" },
			{ value: "git-attributes", label: "Git Attributes" },
			{ value: "git-config", label: "Git Config" },
			{ value: "glsl", label: "GLSL" },
			{ value: "glyph", label: "Glyph" },
			{
				value: "glyph-bitmap-distribution-format",
				label: "Glyph Bitmap Distribution Format",
			},
			{ value: "gn", label: "GN" },
			{ value: "gnuplot", label: "Gnuplot" },
			{ value: "go", label: "Go" },
			{ value: "go-checksums", label: "Go Checksums" },
			{ value: "go-module", label: "Go Module" },
			{ value: "golo", label: "Golo" },
			{ value: "gosu", label: "Gosu" },
			{ value: "grace", label: "Grace" },
			{ value: "gradle", label: "Gradle" },
			{ value: "grammatical-framework", label: "Grammatical Framework" },
			{ value: "graph-modeling-language", label: "Graph Modeling Language" },
			{ value: "graphql", label: "GraphQL" },
			{ value: "graphviz-(dot)", label: "Graphviz (DOT)" },
			{ value: "groovy", label: "Groovy" },
			{ value: "groovy-server-pages", label: "Groovy Server Pages" },
			{ value: "hack", label: "Hack" },
			{ value: "haml", label: "Haml" },
			{ value: "handlebars", label: "Handlebars" },
			{ value: "haproxy", label: "HAProxy" },
			{ value: "harbour", label: "Harbour" },
			{ value: "haskell", label: "Haskell" },
			{ value: "haxe", label: "Haxe" },
			{ value: "hcl", label: "HCL" },
			{ value: "hiveql", label: "HiveQL" },
			{ value: "hlsl", label: "HLSL" },
			{ value: "holyc", label: "HolyC" },
			{ value: "jinja", label: "Jinja" },
			{ value: "html+ecr", label: "HTML+ECR" },
			{ value: "html+eex", label: "HTML+EEX" },
			{ value: "html+erb", label: "HTML+ERB" },
			{ value: "html+php", label: "HTML+PHP" },
			{ value: "html+razor", label: "HTML+Razor" },
			{ value: "http", label: "HTTP" },
			{ value: "hxml", label: "HXML" },
			{ value: "hy", label: "Hy" },
			{ value: "hyphy", label: "HyPhy" },
			{ value: "idl", label: "IDL" },
			{ value: "idris", label: "Idris" },
			{ value: "ignore-list", label: "Ignore List" },
			{ value: "igor-pro", label: "IGOR Pro" },
			{ value: "imagej-macro", label: "ImageJ Macro" },
			{ value: "inform-7", label: "Inform 7" },
			{ value: "ini", label: "INI" },
			{ value: "inno-setup", label: "Inno Setup" },
			{ value: "io", label: "Io" },
			{ value: "ioke", label: "Ioke" },
			{ value: "irc-log", label: "IRC log" },
			{ value: "isabelle", label: "Isabelle" },
			{ value: "isabelle-root", label: "Isabelle ROOT" },
			{ value: "j", label: "J" },
			{ value: "jasmin", label: "Jasmin" },
			{ value: "java-properties", label: "Java Properties" },
			{ value: "java-server-pages", label: "Java Server Pages" },
			{ value: "javascript+erb", label: "JavaScript+ERB" },
			{ value: "jflex", label: "JFlex" },
			{ value: "jinja", label: "Jinja" },
			{ value: "jison", label: "Jison" },
			{ value: "jison-lex", label: "Jison Lex" },
			{ value: "jolie", label: "Jolie" },
			{ value: "jq", label: "jq" },
			{ value: "json", label: "JSON" },
			{ value: "json-with-comments", label: "JSON with Comments" },
			{ value: "json5", label: "JSON5" },
			{ value: "jsoniq", label: "JSONiq" },
			{ value: "jsonld", label: "JSONLD" },
			{ value: "jsonnet", label: "Jsonnet" },
			{ value: "julia", label: "Julia" },
			{ value: "jupyter-notebook", label: "Jupyter Notebook" },
			{ value: "kaitai-struct", label: "Kaitai Struct" },
			{ value: "kakounescript", label: "KakouneScript" },
			{ value: "kicad-layout", label: "KiCad Layout" },
			{ value: "kicad-legacy-layout", label: "KiCad Legacy Layout" },
			{ value: "kicad-schematic", label: "KiCad Schematic" },
			{ value: "kit", label: "Kit" },
			{ value: "kotlin", label: "Kotlin" },
			{ value: "krl", label: "KRL" },
			{ value: "kusto", label: "Kusto" },
			{ value: "labview", label: "LabVIEW" },
			{ value: "lark", label: "Lark" },
			{ value: "lasso", label: "Lasso" },
			{ value: "latte", label: "Latte" },
			{ value: "lean", label: "Lean" },
			{ value: "less", label: "Less" },
			{ value: "lex", label: "Lex" },
			{ value: "lfe", label: "LFE" },
			{ value: "lilypond", label: "LilyPond" },
			{ value: "limbo", label: "Limbo" },
			{ value: "linker-script", label: "Linker Script" },
			{ value: "linux-kernel-module", label: "Linux Kernel Module" },
			{ value: "liquid", label: "Liquid" },
			{ value: "literate-agda", label: "Literate Agda" },
			{ value: "literate-coffeescript", label: "Literate CoffeeScript" },
			{ value: "literate-haskell", label: "Literate Haskell" },
			{ value: "livescript", label: "LiveScript" },
			{ value: "llvm", label: "LLVM" },
			{ value: "logos", label: "Logos" },
			{ value: "logtalk", label: "Logtalk" },
			{ value: "lolcode", label: "LOLCODE" },
			{ value: "lookml", label: "LookML" },
			{ value: "loomscript", label: "LoomScript" },
			{ value: "lsl", label: "LSL" },
			{ value: "ltspice-symbol", label: "LTspice Symbol" },
			{ value: "lua", label: "Lua" },
			{ value: "m", label: "M" },
			{ value: "m4", label: "M4" },
			{ value: "m4sugar", label: "M4Sugar" },
			{ value: "macaulay2", label: "Macaulay2" },
			{ value: "makefile", label: "Makefile" },
			{ value: "mako", label: "Mako" },
			{ value: "markdown", label: "Markdown" },
			{ value: "marko", label: "Marko" },
			{ value: "mask", label: "Mask" },
			{ value: "mathematica", label: "Mathematica" },
			{ value: "matlab", label: "MATLAB" },
			{ value: "maven-pom", label: "Maven POM" },
			{ value: "max", label: "Max" },
			{ value: "maxscript", label: "MAXScript" },
			{ value: "mcfunction", label: "mcfunction" },
			{ value: "wikitext", label: "Wikitext" },
			{ value: "mercury", label: "Mercury" },
			{ value: "meson", label: "Meson" },
			{ value: "metal", label: "Metal" },
			{
				value: "microsoft-developer-studio-project",
				label: "Microsoft Developer Studio Project",
			},
			{
				value: "microsoft-visual-studio-solution",
				label: "Microsoft Visual Studio Solution",
			},
			{ value: "minid", label: "MiniD" },
			{ value: "mirah", label: "Mirah" },
			{ value: "mirc-script", label: "mIRC Script" },
			{ value: "mlir", label: "MLIR" },
			{ value: "modelica", label: "Modelica" },
			{ value: "modula-2", label: "Modula-2" },
			{ value: "modula-3", label: "Modula-3" },
			{ value: "module-management-system", label: "Module Management System" },
			{ value: "monkey", label: "Monkey" },
			{ value: "moocode", label: "Moocode" },
			{ value: "moonscript", label: "MoonScript" },
			{ value: "motoko", label: "Motoko" },
			{ value: "motorola-68k-assembly", label: "Motorola 68K Assembly" },
			{ value: "mql4", label: "MQL4" },
			{ value: "mql5", label: "MQL5" },
			{ value: "mtml", label: "MTML" },
			{ value: "muf", label: "MUF" },
			{ value: "mupad", label: "mupad" },
			{ value: "muse", label: "Muse" },
			{ value: "mustache", label: "Mustache" },
			{ value: "myghty", label: "Myghty" },
			{ value: "nanorc", label: "nanorc" },
			{ value: "nasl", label: "NASL" },
			{ value: "ncl", label: "NCL" },
			{ value: "nearley", label: "Nearley" },
			{ value: "nemerle", label: "Nemerle" },
			{ value: "neon", label: "NEON" },
			{ value: "nesc", label: "nesC" },
			{ value: "netlinx", label: "NetLinx" },
			{ value: "netlinx+erb", label: "NetLinx+ERB" },
			{ value: "netlogo", label: "NetLogo" },
			{ value: "newlisp", label: "NewLisp" },
			{ value: "nextflow", label: "Nextflow" },
			{ value: "nginx", label: "Nginx" },
			{ value: "nim", label: "Nim" },
			{ value: "ninja", label: "Ninja" },
			{ value: "nit", label: "Nit" },
			{ value: "nix", label: "Nix" },
			{ value: "nl", label: "NL" },
			{ value: "npm-config", label: "NPM Config" },
			{ value: "nsis", label: "NSIS" },
			{ value: "nu", label: "Nu" },
			{ value: "numpy", label: "NumPy" },
			{ value: "nunjucks", label: "Nunjucks" },
			{ value: "nwscript", label: "NWScript" },
			{ value: "objdump", label: "ObjDump" },
			{
				value: "object-data-instance-notation",
				label: "Object Data Instance Notation",
			},
			{ value: "objective-c", label: "Objective-C" },
			{ value: "objective-c++", label: "Objective-C++" },
			{ value: "objective-j", label: "Objective-J" },
			{ value: "objectscript", label: "ObjectScript" },
			{ value: "ocaml", label: "OCaml" },
			{ value: "odin", label: "Odin" },
			{ value: "omgrofl", label: "Omgrofl" },
			{ value: "ooc", label: "ooc" },
			{ value: "opa", label: "Opa" },
			{ value: "opal", label: "Opal" },
			{ value: "open-policy-agent", label: "Open Policy Agent" },
			{ value: "opencl", label: "OpenCL" },
			{ value: "openedge-abl", label: "OpenEdge ABL" },
			{ value: "openqasm", label: "OpenQASM" },
			{ value: "openrc-runscript", label: "OpenRC runscript" },
			{ value: "openscad", label: "OpenSCAD" },
			{ value: "openstep-property-list", label: "OpenStep Property List" },
			{ value: "opentype-feature-file", label: "OpenType Feature File" },
			{ value: "org", label: "Org" },
			{ value: "ox", label: "Ox" },
			{ value: "oxygene", label: "Oxygene" },
			{ value: "oz", label: "Oz" },
			{ value: "p4", label: "P4" },
			{ value: "pan", label: "Pan" },
			{ value: "papyrus", label: "Papyrus" },
			{ value: "parrot", label: "Parrot" },
			{ value: "parrot-assembly", label: "Parrot Assembly" },
			{
				value: "parrot-internal-representation",
				label: "Parrot Internal Representation",
			},
			{ value: "pascal", label: "Pascal" },
			{ value: "pawn", label: "Pawn" },
			{ value: "peg.js", label: "PEG.js" },
			{ value: "pep8", label: "Pep8" },
			{ value: "perl", label: "Perl" },
			{ value: "pic", label: "Pic" },
			{ value: "pickle", label: "Pickle" },
			{ value: "picolisp", label: "PicoLisp" },
			{ value: "piglatin", label: "PigLatin" },
			{ value: "pike", label: "Pike" },
			{ value: "plantuml", label: "PlantUML" },
			{ value: "plpgsql", label: "PLpgSQL" },
			{ value: "plsql", label: "PLSQL" },
			{ value: "pod", label: "Pod" },
			{ value: "pod-6", label: "Pod 6" },
			{ value: "pogoscript", label: "PogoScript" },
			{ value: "pony", label: "Pony" },
			{ value: "postcss", label: "PostCSS" },
			{ value: "postscript", label: "PostScript" },
			{ value: "pov-ray-sdl", label: "POV-Ray SDL" },
			{ value: "powerbuilder", label: "PowerBuilder" },
			{ value: "powershell", label: "PowerShell" },
			{ value: "prisma", label: "Prisma" },
			{ value: "processing", label: "Processing" },
			{ value: "proguard", label: "Proguard" },
			{ value: "prolog", label: "Prolog" },
			{ value: "promela", label: "Promela" },
			{ value: "propeller-spin", label: "Propeller Spin" },
			{ value: "protocol-buffer", label: "Protocol Buffer" },
			{ value: "public-key", label: "Public Key" },
			{ value: "pug", label: "Pug" },
			{ value: "puppet", label: "Puppet" },
			{ value: "pure-data", label: "Pure Data" },
			{ value: "purebasic", label: "PureBasic" },
			{ value: "purescript", label: "PureScript" },
			{ value: "python-console", label: "Python console" },
			{ value: "python-traceback", label: "Python traceback" },
			{ value: "q", label: "q" },
			{ value: "q%23", label: "Q#" },
			{ value: "qmake", label: "QMake" },
			{ value: "qml", label: "QML" },
			{ value: "qt-script", label: "Qt Script" },
			{ value: "quake", label: "Quake" },
			{ value: "r", label: "R" },
			{ value: "racket", label: "Racket" },
			{ value: "ragel", label: "Ragel" },
			{ value: "raku", label: "Raku" },
			{ value: "raml", label: "RAML" },
			{ value: "rascal", label: "Rascal" },
			{ value: "raw-token-data", label: "Raw token data" },
			{ value: "rdoc", label: "RDoc" },
			{ value: "readline-config", label: "Readline Config" },
			{ value: "realbasic", label: "REALbasic" },
			{ value: "reason", label: "Reason" },
			{ value: "rebol", label: "Rebol" },
			{ value: "red", label: "Red" },
			{ value: "redcode", label: "Redcode" },
			{ value: "regular-expression", label: "Regular Expression" },
			{ value: "ren'py", label: "Ren'Py" },
			{ value: "renderscript", label: "RenderScript" },
			{ value: "rescript", label: "ReScript" },
			{ value: "restructuredtext", label: "reStructuredText" },
			{ value: "rexx", label: "REXX" },
			{ value: "rich-text-format", label: "Rich Text Format" },
			{ value: "ring", label: "Ring" },
			{ value: "riot", label: "Riot" },
			{ value: "rmarkdown", label: "RMarkdown" },
			{ value: "robotframework", label: "RobotFramework" },
			{ value: "robots.txt", label: "robots.txt" },
			{ value: "roff", label: "Roff" },
			{ value: "roff-manpage", label: "Roff Manpage" },
			{ value: "rouge", label: "Rouge" },
			{ value: "rpc", label: "RPC" },
			{ value: "rpm-spec", label: "RPM Spec" },
			{ value: "runoff", label: "RUNOFF" },
			{ value: "rust", label: "Rust" },
			{ value: "sage", label: "Sage" },
			{ value: "saltstack", label: "SaltStack" },
			{ value: "sas", label: "SAS" },
			{ value: "sass", label: "Sass" },
			{ value: "scala", label: "Scala" },
			{ value: "scaml", label: "Scaml" },
			{ value: "scheme", label: "Scheme" },
			{ value: "scilab", label: "Scilab" },
			{ value: "scss", label: "SCSS" },
			{ value: "sed", label: "sed" },
			{ value: "self", label: "Self" },
			{ value: "shaderlab", label: "ShaderLab" },
			{ value: "shell", label: "Shell" },
			{ value: "shellsession", label: "ShellSession" },
			{ value: "shen", label: "Shen" },
			{ value: "sieve", label: "Sieve" },
			{ value: "singularity", label: "Singularity" },
			{ value: "slash", label: "Slash" },
			{ value: "slice", label: "Slice" },
			{ value: "slim", label: "Slim" },
			{ value: "smali", label: "Smali" },
			{ value: "smalltalk", label: "Smalltalk" },
			{ value: "smarty", label: "Smarty" },
			{ value: "smpl", label: "SmPL" },
			{ value: "smt", label: "SMT" },
			{ value: "solidity", label: "Solidity" },
			{ value: "sourcepawn", label: "SourcePawn" },
			{ value: "sparql", label: "SPARQL" },
			{ value: "spline-font-database", label: "Spline Font Database" },
			{ value: "sqf", label: "SQF" },
			{ value: "sql", label: "SQL" },
			{ value: "sqlpl", label: "SQLPL" },
			{ value: "squirrel", label: "Squirrel" },
			{ value: "srecode-template", label: "SRecode Template" },
			{ value: "ssh-config", label: "SSH Config" },
			{ value: "stan", label: "Stan" },
			{ value: "standard-ml", label: "Standard ML" },
			{ value: "starlark", label: "Starlark" },
			{ value: "stata", label: "Stata" },
			{ value: "ston", label: "STON" },
			{ value: "stringtemplate", label: "StringTemplate" },
			{ value: "stylus", label: "Stylus" },
			{ value: "subrip-text", label: "SubRip Text" },
			{ value: "sugarss", label: "SugarSS" },
			{ value: "supercollider", label: "SuperCollider" },
			{ value: "svelte", label: "Svelte" },
			{ value: "svg", label: "SVG" },
			{ value: "swift", label: "Swift" },
			{ value: "swig", label: "SWIG" },
			{ value: "systemverilog", label: "SystemVerilog" },
			{ value: "tcl", label: "Tcl" },
			{ value: "tcsh", label: "Tcsh" },
			{ value: "tea", label: "Tea" },
			{ value: "terra", label: "Terra" },
			{ value: "tex", label: "TeX" },
			{ value: "texinfo", label: "Texinfo" },
			{ value: "text", label: "Text" },
			{ value: "textile", label: "Textile" },
			{ value: "thrift", label: "Thrift" },
			{ value: "ti-program", label: "TI Program" },
			{ value: "tla", label: "TLA" },
			{ value: "toml", label: "TOML" },
			{ value: "tsql", label: "TSQL" },
			{ value: "tsv", label: "TSV" },
			{ value: "tsx", label: "TSX" },
			{ value: "turing", label: "Turing" },
			{ value: "turtle", label: "Turtle" },
			{ value: "twig", label: "Twig" },
			{ value: "txl", label: "TXL" },
			{ value: "type-language", label: "Type Language" },
			{ value: "typescript", label: "TypeScript" },
			{ value: "unified-parallel-c", label: "Unified Parallel C" },
			{ value: "unity3d-asset", label: "Unity3D Asset" },
			{ value: "unix-assembly", label: "Unix Assembly" },
			{ value: "uno", label: "Uno" },
			{ value: "unrealscript", label: "UnrealScript" },
			{ value: "urweb", label: "UrWeb" },
			{ value: "v", label: "V" },
			{ value: "vala", label: "Vala" },
			{ value: "valve-data-format", label: "Valve Data Format" },
			{ value: "vba", label: "VBA" },
			{ value: "vbscript", label: "VBScript" },
			{ value: "vcl", label: "VCL" },
			{ value: "verilog", label: "Verilog" },
			{ value: "vhdl", label: "VHDL" },
			{ value: "vim-help-file", label: "Vim Help File" },
			{ value: "vim-script", label: "Vim Script" },
			{ value: "vim-snippet", label: "Vim Snippet" },
			{ value: "visual-basic-.net", label: "Visual Basic .NET" },
			{ value: "visual-basic-.net", label: "Visual Basic .NET" },
			{ value: "volt", label: "Volt" },
			{ value: "vue", label: "Vue" },
			{ value: "wavefront-material", label: "Wavefront Material" },
			{ value: "wavefront-object", label: "Wavefront Object" },
			{ value: "wdl", label: "wdl" },
			{ value: "web-ontology-language", label: "Web Ontology Language" },
			{ value: "webassembly", label: "WebAssembly" },
			{ value: "webidl", label: "WebIDL" },
			{ value: "webvtt", label: "WebVTT" },
			{ value: "wget-config", label: "Wget Config" },
			{ value: "wikitext", label: "Wikitext" },
			{ value: "windows-registry-entries", label: "Windows Registry Entries" },
			{ value: "wisp", label: "wisp" },
			{ value: "wollok", label: "Wollok" },
			{
				value: "world-of-warcraft-addon-data",
				label: "World of Warcraft Addon Data",
			},
			{ value: "x-bitmap", label: "X BitMap" },
			{ value: "x-font-directory-index", label: "X Font Directory Index" },
			{ value: "x-pixmap", label: "X PixMap" },
			{ value: "x10", label: "X10" },
			{ value: "xbase", label: "xBase" },
			{ value: "xc", label: "XC" },
			{ value: "xcompose", label: "XCompose" },
			{ value: "xml", label: "XML" },
			{ value: "xml-property-list", label: "XML Property List" },
			{ value: "xojo", label: "Xojo" },
			{ value: "xonsh", label: "Xonsh" },
			{ value: "xpages", label: "XPages" },
			{ value: "xproc", label: "XProc" },
			{ value: "xquery", label: "XQuery" },
			{ value: "xs", label: "XS" },
			{ value: "xslt", label: "XSLT" },
			{ value: "xtend", label: "Xtend" },
			{ value: "yacc", label: "Yacc" },
			{ value: "yaml", label: "YAML" },
			{ value: "yang", label: "YANG" },
			{ value: "yara", label: "YARA" },
			{ value: "yasnippet", label: "YASnippet" },
			{ value: "zap", label: "ZAP" },
			{ value: "zeek", label: "Zeek" },
			{ value: "zenscript", label: "ZenScript" },
			{ value: "zephir", label: "Zephir" },
			{ value: "zig", label: "Zig" },
			{ value: "zil", label: "ZIL" },
			{ value: "zimpl", label: "Zimpl" },
		],
	},
	{
		range: "date",
		label: "Date range",
		active: true,
		selected: "daily",
		param: "since",
		categories: [
			{ value: "daily", label: "Today" },
			{ value: "weekly", label: "This week" },
			{ value: "monthly", label: "This month" },
		],
	},
];
